### ISSUE TITLE
negotiated_rates -> service_code should not be a required field

### ISSUE THREAD

**Issue by rakeshkatte** [CMSgov/price-transparency-guide#121]
In-network file: As the place of service code is a required field only for the professional claim type, this field should be considered a conditionally required field instead of a required field. OR please specify a default value that needs to be used for the institutional claims (ex: 99?).

Allowed_Amounts file: Same applies here too.

**Comment by ryan-thomas-peterson** [comment]
Agree on this one too.

**Comment by rgouldkc** [comment]
Agree as well. For professional claims most contracts don't care what the service code is, the one exception being some Urgent Care contracts that have a special fee schedule for some procedures done in an Urgent Care facility code 20. The same procedure done in a different facility such as a doctors off code 11 under that contract uses a standard "don't care about facility type" rate. 

For Institutional claims they basically break down to Inpatient, Outpatient, and Ambulatory Surgical Center.

My thoughts recently aside from a service code array would be for Professional leave service code blank when it doesn't matter and when it does specify the service code. For Institutional something as simple as INP for Inpatient, OTP for Outpatient and ASC for Ambulatory Surgical Center would suffice with the option of leaving service code blank for Institutional as well when it does not apply.

**Comment by narenlulla** [comment]
Institutional claims have a TOB (Type of Bill) where the first digit is always 0 (by custom not used and 3-digit codes are universally used) second is type of facility 1 = hospital 2 = SNF etc. The 3rd digit is 1=Inpatient 3 = Outpatient.
AMBSURG is a type of facility INPAT/OUTPT is type of care, they don't mix

Most contracts don't have POS differentials, it should be mandatory only if there is a differential for example if a virtual visit is paid differently than a in-person visit

**Comment by shaselton-usds** [comment]
`billing_class` has been introduced some time ago to address this issue. Closing.

**Comment by narenlulla** [comment]
billing_class does not address the issue, billing_class professional still has place of service as a mandatory field. This assumes all physician contracts have POS differrentials, a lot of plans are entering the entire list of POS codes in an aray for each code in the fee schedule to be compliant (if the contract does not specify POS it is valid for all POS and since there is no ALL-POS let's put them all in an array is the thinking) which is making the files unnecessarily large.

Please read and understand the issue fully and ask for comments before unilaterally closing issues
