### ISSUE TITLE
CMS Schema Files Will Not Import and Compile in Informatica – Return as Invalid/Corrupt

### ISSUE THREAD

**Issue by kchaganti23** [CMSgov/price-transparency-guide#335]
``None of the schema files provided by CMS will import and compile using Informatica, including the most recent dated 12/17/2021. Attempts error out indicating that the file format is “Invalid,” see the screenshot, below. This issue was escalated to Informatica Support, who confirmed that the files are “corrupt” and cannot be imported and compiled.

![screenshot](https://user-images.githubusercontent.com/97055254/148278145-de39a697-ab17-4b7a-9f9f-ecc3f33c3597.jpg)

Have any other organizations been able to import and compile the CMS-provided schema files using Informatica or any other tool?
We currently have to reverse-engineer schema files from CMS-provided sample data files.

**Comment by garysolebc** [comment]
Doing a quick search against JSON schema validation with Informatica, it appears that Informatica supports draft-03 of the schema, whereas the schema being presented by CMS is draft-07.  I suspect this is the problem with Informatica import only supporting draft-03.  
Can you confirm whether Informatica is capable of processing draft-07 of the schema?

A potential solution would be to try and edit the file down to a draft-03 version in order to import it, or do the reverse engineer, but then update it with the appropriate enumerations and any additional structure that would not be picked up by a reverse engineer as the sample does not have all possible structure and enumerations included.

**Comment by shaselton-usds** [comment]
Thanks @garysolebc. Yes, the schema is based on draft-07 and is definitely leveraging 07 features, so Informatica might be difficult to work with.
